export const themeSettings = {
	// Set this to the theme id you want to use as the starter default.
	defaultThemeId: "retro-blue",
	// Disable this for production sites that should not expose theme choices.
	showThemeSwitcher: true,
	// Disable this with showThemeSwitcher when you want the configured default to always win.
	persistUserSelection: true,
	storageKey: "theme_id",
	cookieName: "theme_id",
};

export const defaultThemeId = themeSettings.defaultThemeId;
export const showThemeSwitcher = themeSettings.showThemeSwitcher;

export const themes = [
	{
		id: "retro-blue",
		name: "Retro Blue",
		description:
			"The original RicoUI palette: warm canvas, editorial blue headings, gold highlights, and calm slate neutrals.",
		source: "Current default theme",
		designDoc: "docs/DESIGN/retro-blue.md",
		swatches: ["#2d6dc3", "#8fb9ff", "#fad13b", "#fdfaf5", "#0b1220"],
		lightSwatches: ["#2d6dc3", "#0066ff", "#8fb9ff", "#fad13b", "#fdfaf5", "#ffffff"],
		darkSwatches: ["#3884eb", "#8fb9ff", "#bcd8ff", "#faeb75", "#0b1220", "#0f1b2d"],
		tokens: {
			light: {
				"--color-primary": "#2d6dc3",
				"--color-primary-rgb": "45, 109, 195",
				"--color-primary-strong": "#0066ff",
				"--color-primary-dark": "#2d6dc3",
				"--color-primary-light": "#8fb9ff",
				"--color-primary-light-dark": "#bcd8ff",
				"--color-primary-lighter": "#6da7ff",
				"--color-primary-bg": "var(--color-bg-primary-light)",
				"--color-primary-bg-light": "var(--color-bg-secondary)",
				"--color-accent": "#fad13b",
				"--color-accent-rgb": "250, 209, 59",
				"--color-accent-light": "#faeb75",
				"--color-bg-primary": "#fdfaf5",
				"--color-bg-secondary": "#ffffff",
				"--color-bg-primary-light": "#faf9f5",
				"--color-bg-primary-deep": "#fefcf4",
				"--color-bg-primary-dark": "#0b1220",
				"--color-bg-secondary-dark": "#0f1b2d",
				"--color-text-primary": "#2d6dc3",
				"--color-text-secondary": "#3f4a5a",
				"--color-text-tertiary": "#7a6550",
				"--color-text-primary-dark": "#3884eb",
				"--color-text-secondary-dark": "#c5cedb",
				"--color-text-tertiary-dark": "#9bb3d7",
				"--color-btn-primary": "#2d6dc3",
				"--color-btn-primary-hover": "#0066ff",
				"--color-btn-primary-dark": "#2871e9",
				"--color-btn-primary-dark-hover": "#2d6dc3",
				"--color-btn-primary-text": "#ffffff",
			},
			dark: {
				"--color-primary": "#3884eb",
				"--color-primary-rgb": "56, 132, 235",
				"--color-primary-strong": "#8fb9ff",
				"--color-primary-light": "#bcd8ff",
				"--color-primary-dark": "#3884eb",
				"--color-primary-light-dark": "#3884eb",
				"--color-primary-lighter": "#8fb9ff",
				"--color-primary-bg": "rgba(56, 132, 235, 0.15)",
				"--color-primary-bg-light": "rgba(56, 132, 235, 0.05)",
				"--color-accent": "#faeb75",
				"--color-accent-rgb": "250, 235, 117",
				"--color-accent-light": "#faeb75",
				"--color-bg-primary": "#0b1220",
				"--color-bg-secondary": "#0f1b2d",
				"--color-bg-primary-light": "#101b2b",
				"--color-bg-primary-deep": "#08101d",
				"--color-bg-primary-dark": "#0b1220",
				"--color-bg-secondary-dark": "#0f1b2d",
				"--color-text-primary": "#3884eb",
				"--color-text-secondary": "#c5cedb",
				"--color-text-tertiary": "#9bb3d7",
				"--color-text-primary-dark": "#3884eb",
				"--color-text-secondary-dark": "#c5cedb",
				"--color-text-tertiary-dark": "#9bb3d7",
				"--color-btn-primary": "#2871e9",
				"--color-btn-primary-hover": "#3884eb",
				"--color-btn-primary-dark": "#2871e9",
				"--color-btn-primary-dark-hover": "#3884eb",
				"--color-btn-primary-text": "#ffffff",
			},
		},
	},
	{
		id: "minimal-mono",
		name: "Minimal Mono",
		description:
			"A restrained black, white, and warm gray theme inspired by the color discipline in docs/DESIGN/basic.md.",
		source: "docs/DESIGN/basic.md color palette",
		designDoc: "docs/DESIGN/minimal-mono.md",
		swatches: ["#1a1a1a", "#777169", "#e5e5e5", "#fdfcfc", "#f5f3f1"],
		lightSwatches: ["#1a1a1a", "#333333", "#b1b0b0", "#f5f3f1", "#fdfcfc", "#ffffff"],
		darkSwatches: ["#f4f4f2", "#ffffff", "#d2d2cf", "#2a2927", "#11110f", "#1a1917"],
		tokens: {
			light: {
				"--color-primary": "#1a1a1a",
				"--color-primary-rgb": "26, 26, 26",
				"--color-primary-strong": "#333333",
				"--color-primary-dark": "#1a1a1a",
				"--color-primary-light": "#b1b0b0",
				"--color-primary-light-dark": "#d2d2cf",
				"--color-primary-lighter": "#d8d5cf",
				"--color-primary-bg": "#f5f3f1",
				"--color-primary-bg-light": "#ffffff",
				"--color-accent": "#f5f3f1",
				"--color-accent-rgb": "245, 243, 241",
				"--color-accent-light": "#e5e5e5",
				"--color-bg-primary": "#fdfcfc",
				"--color-bg-secondary": "#ffffff",
				"--color-bg-primary-light": "#f5f3f1",
				"--color-bg-primary-deep": "#fbfaf8",
				"--color-bg-primary-dark": "#11110f",
				"--color-bg-secondary-dark": "#1a1917",
				"--color-text-primary": "#1a1a1a",
				"--color-text-secondary": "#57534f",
				"--color-text-tertiary": "#777169",
				"--color-text-primary-dark": "#f4f4f2",
				"--color-text-secondary-dark": "#d8d5cf",
				"--color-text-tertiary-dark": "#aaa49b",
				"--color-btn-primary": "#1a1a1a",
				"--color-btn-primary-hover": "#333333",
				"--color-btn-primary-dark": "#f4f4f2",
				"--color-btn-primary-dark-hover": "#ffffff",
				"--color-btn-primary-text": "#ffffff",
			},
			dark: {
				"--color-primary": "#f4f4f2",
				"--color-primary-rgb": "244, 244, 242",
				"--color-primary-strong": "#ffffff",
				"--color-primary-light": "#d2d2cf",
				"--color-primary-dark": "#f4f4f2",
				"--color-primary-light-dark": "#f4f4f2",
				"--color-primary-lighter": "#d8d5cf",
				"--color-primary-bg": "rgba(244, 244, 242, 0.12)",
				"--color-primary-bg-light": "rgba(244, 244, 242, 0.06)",
				"--color-accent": "#2a2927",
				"--color-accent-rgb": "42, 41, 39",
				"--color-accent-light": "#363532",
				"--color-bg-primary": "#11110f",
				"--color-bg-secondary": "#1a1917",
				"--color-bg-primary-light": "#151411",
				"--color-bg-primary-deep": "#0d0d0c",
				"--color-bg-primary-dark": "#11110f",
				"--color-bg-secondary-dark": "#1a1917",
				"--color-text-primary": "#f4f4f2",
				"--color-text-secondary": "#d8d5cf",
				"--color-text-tertiary": "#aaa49b",
				"--color-text-primary-dark": "#f4f4f2",
				"--color-text-secondary-dark": "#d8d5cf",
				"--color-text-tertiary-dark": "#aaa49b",
				"--color-btn-primary": "#f4f4f2",
				"--color-btn-primary-hover": "#ffffff",
				"--color-btn-primary-dark": "#f4f4f2",
				"--color-btn-primary-dark-hover": "#ffffff",
				"--color-btn-primary-text": "#11110f",
			},
		},
	},
	{
		id: "forest-green",
		name: "Forest Green",
		description:
			"A quiet green theme inspired by docs/DESIGN/green.md: ink text, paper surfaces, and a grounded botanical accent.",
		source: "docs/DESIGN/green.md color palette",
		designDoc: "docs/DESIGN/forest-green.md",
		swatches: ["#4a7c59", "#6f9f7a", "#f5f2ee", "#ffffff", "#121212"],
		lightSwatches: ["#4a7c59", "#356644", "#8fba98", "#dce9d8", "#f7f5f0", "#ffffff"],
		darkSwatches: ["#91c89d", "#b8ddb8", "#cfe8d1", "#263e2d", "#0f1712", "#162119"],
		tokens: {
			light: {
				"--color-primary": "#4a7c59",
				"--color-primary-rgb": "74, 124, 89",
				"--color-primary-strong": "#356644",
				"--color-primary-dark": "#4a7c59",
				"--color-primary-light": "#8fba98",
				"--color-primary-light-dark": "#cfe8d1",
				"--color-primary-lighter": "#b8ddb8",
				"--color-primary-bg": "#eef5ea",
				"--color-primary-bg-light": "#f7f5f0",
				"--color-accent": "#dce9d8",
				"--color-accent-rgb": "220, 233, 216",
				"--color-accent-light": "#edf6e9",
				"--color-bg-primary": "#f7f5f0",
				"--color-bg-secondary": "#ffffff",
				"--color-bg-primary-light": "#f5f2ee",
				"--color-bg-primary-deep": "#fbfaf6",
				"--color-bg-primary-dark": "#0f1712",
				"--color-bg-secondary-dark": "#162119",
				"--color-text-primary": "#2f6840",
				"--color-text-secondary": "#33443a",
				"--color-text-tertiary": "#66736a",
				"--color-text-primary-dark": "#91c89d",
				"--color-text-secondary-dark": "#d5ded7",
				"--color-text-tertiary-dark": "#9daf9f",
				"--color-btn-primary": "#4a7c59",
				"--color-btn-primary-hover": "#356644",
				"--color-btn-primary-dark": "#6f9f7a",
				"--color-btn-primary-dark-hover": "#91c89d",
				"--color-btn-primary-text": "#ffffff",
			},
			dark: {
				"--color-primary": "#91c89d",
				"--color-primary-rgb": "145, 200, 157",
				"--color-primary-strong": "#b8ddb8",
				"--color-primary-light": "#cfe8d1",
				"--color-primary-dark": "#91c89d",
				"--color-primary-light-dark": "#91c89d",
				"--color-primary-lighter": "#b8ddb8",
				"--color-primary-bg": "rgba(145, 200, 157, 0.15)",
				"--color-primary-bg-light": "rgba(145, 200, 157, 0.06)",
				"--color-accent": "#263e2d",
				"--color-accent-rgb": "38, 62, 45",
				"--color-accent-light": "#31523a",
				"--color-bg-primary": "#0f1712",
				"--color-bg-secondary": "#162119",
				"--color-bg-primary-light": "#111c15",
				"--color-bg-primary-deep": "#0a120d",
				"--color-bg-primary-dark": "#0f1712",
				"--color-bg-secondary-dark": "#162119",
				"--color-text-primary": "#91c89d",
				"--color-text-secondary": "#d5ded7",
				"--color-text-tertiary": "#9daf9f",
				"--color-text-primary-dark": "#91c89d",
				"--color-text-secondary-dark": "#d5ded7",
				"--color-text-tertiary-dark": "#9daf9f",
				"--color-btn-primary": "#91c89d",
				"--color-btn-primary-hover": "#b8ddb8",
				"--color-btn-primary-dark": "#91c89d",
				"--color-btn-primary-dark-hover": "#b8ddb8",
				"--color-btn-primary-text": "#0f1712",
			},
		},
	},
];

export const themeById = Object.fromEntries(themes.map((theme) => [theme.id, theme]));
