export const themeSettings = {
	// Set this to the theme id you want to use as the starter default.
	defaultThemeId: "retro-blue",
	// Disable this for production sites that should not expose theme choices.
	showThemeSwitcher: true,
	// Disable this with showThemeSwitcher when you want the configured default to always win.
	persistUserSelection: true,
	storageKey: "theme_id",
	cookieName: "theme_id",
};

export const defaultThemeId = themeSettings.defaultThemeId;
export const showThemeSwitcher = themeSettings.showThemeSwitcher;

export const themes = [
	{
		id: "retro-blue",
		name: "Retro Blue",
		description:
			"RicoUI 经典配色：暖调画布、蓝色标题、金色点缀与石板中性色。",
		source: "默认色板",
		designDoc: "docs/DESIGN/retro-blue.md",
		details: {
			atmosphere:
				"暖调编辑风画布，蓝色标题搭配金色点缀，石板中性色收底。",
			bestFor: ["入门站点", "编辑类产品页", "文档站"],
			colorRoles: [
				{ name: "编辑蓝", value: "#2d6dc3", role: "标题、链接和主要操作（Editorial Blue）" },
				{ name: "金色点缀", value: "#fad13b", role: "徽标和次要强调（Gold Highlight）" },
				{ name: "暖白画布", value: "#fdfaf5", role: "浅色页面背景（Warm Canvas）" },
			],
			guidance: [
				"蓝色主导导航、标题和操作按钮，作为视觉主信号。",
				"金色仅作小面积点缀，不要大面积铺色。",
				"保留暖调画布，维持编辑气质。",
			],
		},
		swatches: ["#2d6dc3", "#8fb9ff", "#fad13b", "#fdfaf5", "#0b1220"],
		lightSwatches: ["#2d6dc3", "#0066ff", "#8fb9ff", "#fad13b", "#fdfaf5", "#ffffff"],
		darkSwatches: ["#3884eb", "#8fb9ff", "#bcd8ff", "#faeb75", "#0b1220", "#0f1b2d"],
		tokens: {
			light: {
				"--color-primary": "#2d6dc3",
				"--color-primary-rgb": "45, 109, 195",
				"--color-primary-strong": "#0066ff",
				"--color-primary-dark": "#2d6dc3",
				"--color-primary-light": "#8fb9ff",
				"--color-primary-light-dark": "#bcd8ff",
				"--color-primary-lighter": "#6da7ff",
				"--color-primary-bg": "var(--color-bg-primary-light)",
				"--color-primary-bg-light": "var(--color-bg-secondary)",
				"--color-accent": "#fad13b",
				"--color-accent-rgb": "250, 209, 59",
				"--color-accent-light": "#faeb75",
				"--color-bg-primary": "#fdfaf5",
				"--color-bg-secondary": "#ffffff",
				"--color-bg-primary-light": "#faf9f5",
				"--color-bg-primary-deep": "#fefcf4",
				"--color-bg-primary-dark": "#0b1220",
				"--color-bg-secondary-dark": "#0f1b2d",
				"--color-text-primary": "#2d6dc3",
				"--color-text-secondary": "#3f4a5a",
				"--color-text-tertiary": "#7a6550",
				"--color-text-primary-dark": "#3884eb",
				"--color-text-secondary-dark": "#c5cedb",
				"--color-text-tertiary-dark": "#9bb3d7",
				"--color-btn-primary": "#2d6dc3",
				"--color-btn-primary-hover": "#0066ff",
				"--color-btn-primary-dark": "#2871e9",
				"--color-btn-primary-dark-hover": "#2d6dc3",
				"--color-btn-primary-text": "#ffffff",
			},
			dark: {
				"--color-primary": "#3884eb",
				"--color-primary-rgb": "56, 132, 235",
				"--color-primary-strong": "#8fb9ff",
				"--color-primary-light": "#bcd8ff",
				"--color-primary-dark": "#3884eb",
				"--color-primary-light-dark": "#3884eb",
				"--color-primary-lighter": "#8fb9ff",
				"--color-primary-bg": "rgba(56, 132, 235, 0.15)",
				"--color-primary-bg-light": "rgba(56, 132, 235, 0.05)",
				"--color-accent": "#faeb75",
				"--color-accent-rgb": "250, 235, 117",
				"--color-accent-light": "#faeb75",
				"--color-bg-primary": "#0b1220",
				"--color-bg-secondary": "#0f1b2d",
				"--color-bg-primary-light": "#101b2b",
				"--color-bg-primary-deep": "#08101d",
				"--color-bg-primary-dark": "#0b1220",
				"--color-bg-secondary-dark": "#0f1b2d",
				"--color-text-primary": "#3884eb",
				"--color-text-secondary": "#c5cedb",
				"--color-text-tertiary": "#9bb3d7",
				"--color-text-primary-dark": "#3884eb",
				"--color-text-secondary-dark": "#c5cedb",
				"--color-text-tertiary-dark": "#9bb3d7",
				"--color-btn-primary": "#2871e9",
				"--color-btn-primary-hover": "#3884eb",
				"--color-btn-primary-dark": "#2871e9",
				"--color-btn-primary-dark-hover": "#3884eb",
				"--color-btn-primary-text": "#ffffff",
			},
		},
	},
	{
		id: "minimal-mono",
		name: "Minimal Mono",
		description:
			"黑白暖灰极简主题，锐利的字重对比，几乎不含饱和色。",
		source: "黑白极简色板",
		designDoc: "docs/DESIGN/minimal-mono.md",
		details: {
			atmosphere:
				"极简单色调，暖灰为主、锐利字重对比，几乎没有饱和色。",
			bestFor: ["编辑类站点", "作品集", "文档站"],
			colorRoles: [
				{ name: "墨色", value: "#1a1a1a", role: "文字、标题和主要控件（Ink）" },
				{ name: "暖灰", value: "#f5f3f1", role: "柔和表面与低调点缀（Warm Gray）" },
				{ name: "纸白", value: "#fdfcfc", role: "浅色页面画布（Paper）" },
			],
			guidance: [
				"不要引入饱和强调色，克制本身就是风格。",
				"用灰色层次区分重点，而非彩色标签。",
				"整体保持安静，适合长文阅读。",
			],
		},
		swatches: ["#1a1a1a", "#777169", "#e5e5e5", "#fdfcfc", "#f5f3f1"],
		lightSwatches: ["#1a1a1a", "#333333", "#b1b0b0", "#f5f3f1", "#fdfcfc", "#ffffff"],
		darkSwatches: ["#f4f4f2", "#ffffff", "#d2d2cf", "#2a2927", "#11110f", "#1a1917"],
		tokens: {
			light: {
				"--color-primary": "#1a1a1a",
				"--color-primary-rgb": "26, 26, 26",
				"--color-primary-strong": "#333333",
				"--color-primary-dark": "#1a1a1a",
				"--color-primary-light": "#b1b0b0",
				"--color-primary-light-dark": "#d2d2cf",
				"--color-primary-lighter": "#d8d5cf",
				"--color-primary-bg": "#f5f3f1",
				"--color-primary-bg-light": "#ffffff",
				"--color-accent": "#f5f3f1",
				"--color-accent-rgb": "245, 243, 241",
				"--color-accent-light": "#e5e5e5",
				"--color-bg-primary": "#fdfcfc",
				"--color-bg-secondary": "#ffffff",
				"--color-bg-primary-light": "#f5f3f1",
				"--color-bg-primary-deep": "#fbfaf8",
				"--color-bg-primary-dark": "#11110f",
				"--color-bg-secondary-dark": "#1a1917",
				"--color-text-primary": "#1a1a1a",
				"--color-text-secondary": "#57534f",
				"--color-text-tertiary": "#777169",
				"--color-text-primary-dark": "#f4f4f2",
				"--color-text-secondary-dark": "#d8d5cf",
				"--color-text-tertiary-dark": "#aaa49b",
				"--color-btn-primary": "#1a1a1a",
				"--color-btn-primary-hover": "#333333",
				"--color-btn-primary-dark": "#f4f4f2",
				"--color-btn-primary-dark-hover": "#ffffff",
				"--color-btn-primary-text": "#ffffff",
			},
			dark: {
				"--color-primary": "#f4f4f2",
				"--color-primary-rgb": "244, 244, 242",
				"--color-primary-strong": "#ffffff",
				"--color-primary-light": "#d2d2cf",
				"--color-primary-dark": "#f4f4f2",
				"--color-primary-light-dark": "#f4f4f2",
				"--color-primary-lighter": "#d8d5cf",
				"--color-primary-bg": "rgba(244, 244, 242, 0.12)",
				"--color-primary-bg-light": "rgba(244, 244, 242, 0.06)",
				"--color-accent": "#2a2927",
				"--color-accent-rgb": "42, 41, 39",
				"--color-accent-light": "#363532",
				"--color-bg-primary": "#11110f",
				"--color-bg-secondary": "#1a1917",
				"--color-bg-primary-light": "#151411",
				"--color-bg-primary-deep": "#0d0d0c",
				"--color-bg-primary-dark": "#11110f",
				"--color-bg-secondary-dark": "#1a1917",
				"--color-text-primary": "#f4f4f2",
				"--color-text-secondary": "#d8d5cf",
				"--color-text-tertiary": "#aaa49b",
				"--color-text-primary-dark": "#f4f4f2",
				"--color-text-secondary-dark": "#d8d5cf",
				"--color-text-tertiary-dark": "#aaa49b",
				"--color-btn-primary": "#f4f4f2",
				"--color-btn-primary-hover": "#ffffff",
				"--color-btn-primary-dark": "#f4f4f2",
				"--color-btn-primary-dark-hover": "#ffffff",
				"--color-btn-primary-text": "#11110f",
			},
		},
	},
	{
		id: "forest-green",
		name: "Forest Green",
		description:
			"沉静的绿色主题，墨色文字搭配纸质表面，植物系点缀。",
		source: "植物色板",
		designDoc: "docs/DESIGN/forest-green.md",
		details: {
			atmosphere:
				"沉稳植物系配色，纸质表面、自然绿与低眩光阅读对比。",
			bestFor: ["知识库", "健康产品", "沉稳产品站"],
			colorRoles: [
				{ name: "森林绿", value: "#4a7c59", role: "品牌色、链接和填充操作（Forest Green）" },
				{ name: "叶绿淡彩", value: "#dce9d8", role: "徽标和柔和点缀（Leaf Tint）" },
				{ name: "纸色", value: "#f7f5f0", role: "浅色页面画布（Paper）" },
			],
			guidance: [
				"绿色作为唯一的色彩方向。",
				"浅绿用在辅助表面，避免用于主要文字。",
				"明暗两套变体都保持自然、低眩光。",
			],
		},
		swatches: ["#4a7c59", "#6f9f7a", "#f5f2ee", "#ffffff", "#121212"],
		lightSwatches: ["#4a7c59", "#356644", "#8fba98", "#dce9d8", "#f7f5f0", "#ffffff"],
		darkSwatches: ["#91c89d", "#b8ddb8", "#cfe8d1", "#263e2d", "#0f1712", "#162119"],
		tokens: {
			light: {
				"--color-primary": "#4a7c59",
				"--color-primary-rgb": "74, 124, 89",
				"--color-primary-strong": "#356644",
				"--color-primary-dark": "#4a7c59",
				"--color-primary-light": "#8fba98",
				"--color-primary-light-dark": "#cfe8d1",
				"--color-primary-lighter": "#b8ddb8",
				"--color-primary-bg": "#eef5ea",
				"--color-primary-bg-light": "#f7f5f0",
				"--color-accent": "#dce9d8",
				"--color-accent-rgb": "220, 233, 216",
				"--color-accent-light": "#edf6e9",
				"--color-bg-primary": "#f7f5f0",
				"--color-bg-secondary": "#ffffff",
				"--color-bg-primary-light": "#f5f2ee",
				"--color-bg-primary-deep": "#fbfaf6",
				"--color-bg-primary-dark": "#0f1712",
				"--color-bg-secondary-dark": "#162119",
				"--color-text-primary": "#2f6840",
				"--color-text-secondary": "#33443a",
				"--color-text-tertiary": "#66736a",
				"--color-text-primary-dark": "#91c89d",
				"--color-text-secondary-dark": "#d5ded7",
				"--color-text-tertiary-dark": "#9daf9f",
				"--color-btn-primary": "#4a7c59",
				"--color-btn-primary-hover": "#356644",
				"--color-btn-primary-dark": "#6f9f7a",
				"--color-btn-primary-dark-hover": "#91c89d",
				"--color-btn-primary-text": "#ffffff",
			},
			dark: {
				"--color-primary": "#91c89d",
				"--color-primary-rgb": "145, 200, 157",
				"--color-primary-strong": "#b8ddb8",
				"--color-primary-light": "#cfe8d1",
				"--color-primary-dark": "#91c89d",
				"--color-primary-light-dark": "#91c89d",
				"--color-primary-lighter": "#b8ddb8",
				"--color-primary-bg": "rgba(145, 200, 157, 0.15)",
				"--color-primary-bg-light": "rgba(145, 200, 157, 0.06)",
				"--color-accent": "#263e2d",
				"--color-accent-rgb": "38, 62, 45",
				"--color-accent-light": "#31523a",
				"--color-bg-primary": "#0f1712",
				"--color-bg-secondary": "#162119",
				"--color-bg-primary-light": "#111c15",
				"--color-bg-primary-deep": "#0a120d",
				"--color-bg-primary-dark": "#0f1712",
				"--color-bg-secondary-dark": "#162119",
				"--color-text-primary": "#91c89d",
				"--color-text-secondary": "#d5ded7",
				"--color-text-tertiary": "#9daf9f",
				"--color-text-primary-dark": "#91c89d",
				"--color-text-secondary-dark": "#d5ded7",
				"--color-text-tertiary-dark": "#9daf9f",
				"--color-btn-primary": "#91c89d",
				"--color-btn-primary-hover": "#b8ddb8",
				"--color-btn-primary-dark": "#91c89d",
				"--color-btn-primary-dark-hover": "#b8ddb8",
				"--color-btn-primary-text": "#0f1712",
			},
		},
	},
	{
		id: "claude",
		name: "Claude",
		description:
			"暖调羊皮纸主题，奶白纸张、精致墨色、内敛边框与小巧陶土色点缀。",
		source: "暖色羊皮纸色板",
		designDoc: "docs/DESIGN/claude.md",
		details: {
			atmosphere:
				"羊皮纸上的学术期刊：温暖米白表面，精准深色文字配低调陶土色点缀。",
			bestFor: ["AI 产品", "研究工具", "写作应用", "知识产品"],
			colorRoles: [
				{ name: "墨黑", value: "#141413", role: "主要文字、标题和深色填充操作（Ink Black）" },
				{ name: "羊皮白", value: "#faf9f5", role: "页面画布和卡片表面（Vellum White）" },
				{ name: "陶土橙", value: "#d97757", role: "小面积点缀和图标细节（Terra Cotta）" },
			],
			guidance: [
				"多用暖色中性表面，避免刺眼的纯白布局。",
				"陶土色保持小面积和克制，整体保持低调。",
				"深色填充按钮表达最清晰的主要操作。",
			],
		},
		swatches: ["#141413", "#3d3d3a", "#d97757", "#faf9f5", "#dedcd1"],
		lightSwatches: ["#141413", "#1f1e1d", "#3d3d3a", "#d97757", "#faf9f5", "#ffffff"],
		darkSwatches: ["#faf9f5", "#dedcd1", "#d97757", "#2a2925", "#141413", "#1f1e1d"],
		tokens: {
			light: {
				"--color-primary": "#141413",
				"--color-primary-rgb": "20, 20, 19",
				"--color-primary-strong": "#1f1e1d",
				"--color-primary-dark": "#141413",
				"--color-primary-light": "#9c9a92",
				"--color-primary-light-dark": "#dedcd1",
				"--color-primary-lighter": "#dedcd1",
				"--color-primary-bg": "#f1eee7",
				"--color-primary-bg-light": "#faf9f5",
				"--color-accent": "#d97757",
				"--color-accent-rgb": "217, 119, 87",
				"--color-accent-light": "#e7b29d",
				"--color-bg-primary": "#faf9f5",
				"--color-bg-secondary": "#ffffff",
				"--color-bg-primary-light": "#f4f1ea",
				"--color-bg-primary-deep": "#fffdf7",
				"--color-bg-primary-dark": "#141413",
				"--color-bg-secondary-dark": "#1f1e1d",
				"--color-text-primary": "#141413",
				"--color-text-secondary": "#3d3d3a",
				"--color-text-tertiary": "#73726c",
				"--color-text-primary-dark": "#faf9f5",
				"--color-text-secondary-dark": "#dedcd1",
				"--color-text-tertiary-dark": "#9c9a92",
				"--color-btn-primary": "#141413",
				"--color-btn-primary-hover": "#1f1e1d",
				"--color-btn-primary-dark": "#faf9f5",
				"--color-btn-primary-dark-hover": "#ffffff",
				"--color-btn-primary-text": "#ffffff",
			},
			dark: {
				"--color-primary": "#faf9f5",
				"--color-primary-rgb": "250, 249, 245",
				"--color-primary-strong": "#ffffff",
				"--color-primary-light": "#dedcd1",
				"--color-primary-dark": "#faf9f5",
				"--color-primary-light-dark": "#faf9f5",
				"--color-primary-lighter": "#dedcd1",
				"--color-primary-bg": "rgba(250, 249, 245, 0.12)",
				"--color-primary-bg-light": "rgba(250, 249, 245, 0.06)",
				"--color-accent": "#d97757",
				"--color-accent-rgb": "217, 119, 87",
				"--color-accent-light": "#e7b29d",
				"--color-bg-primary": "#141413",
				"--color-bg-secondary": "#1f1e1d",
				"--color-bg-primary-light": "#191816",
				"--color-bg-primary-deep": "#0f0f0e",
				"--color-bg-primary-dark": "#141413",
				"--color-bg-secondary-dark": "#1f1e1d",
				"--color-text-primary": "#faf9f5",
				"--color-text-secondary": "#dedcd1",
				"--color-text-tertiary": "#9c9a92",
				"--color-text-primary-dark": "#faf9f5",
				"--color-text-secondary-dark": "#dedcd1",
				"--color-text-tertiary-dark": "#9c9a92",
				"--color-btn-primary": "#faf9f5",
				"--color-btn-primary-hover": "#ffffff",
				"--color-btn-primary-dark": "#faf9f5",
				"--color-btn-primary-dark-hover": "#ffffff",
				"--color-btn-primary-text": "#141413",
			},
		},
	},
	{
		id: "creator-yellow",
		name: "Creator Yellow",
		description:
			"明快的创作者经济配色，灰调画布、白卡片、黑字搭配亮黄色操作。",
		source: "创作者经济色板",
		designDoc: "docs/DESIGN/creator-yellow.md",
		details: {
			atmosphere:
				"轻盈社区画布，白卡片配柔和阴影，亮黄操作色与亲和深色文字。",
			bestFor: ["创作者工具", "社区站点", "支持页面", "电商落地页"],
			colorRoles: [
				{ name: "明黄", value: "#ffdd00", role: "主要操作和品牌强调（Goldenrod）" },
				{ name: "深石墨", value: "#222222", role: "标题和强调正文（Deep Graphite）" },
				{ name: "画布灰", value: "#e5e7eb", role: "柔和页面背景（Canvas Gray）" },
			],
			guidance: [
				"黄色独占主要操作，别加其他饱和色来抢戏。",
				"灰色画布上铺白卡片，保持创作者卡片的触感。",
				"黄配黑，对比干净利落又友好。",
			],
		},
		swatches: ["#ffdd00", "#f7d046", "#d8573f", "#ffffff", "#222222"],
		lightSwatches: ["#ffdd00", "#f7d046", "#d8573f", "#e5e7eb", "#ffffff", "#222222"],
		darkSwatches: ["#ffdd00", "#f7d046", "#d8573f", "#2a2614", "#171510", "#222222"],
		tokens: {
			light: {
				"--color-primary": "#222222",
				"--color-primary-rgb": "34, 34, 34",
				"--color-primary-strong": "#000000",
				"--color-primary-dark": "#222222",
				"--color-primary-light": "#717171",
				"--color-primary-light-dark": "#ffdd00",
				"--color-primary-lighter": "#f7d046",
				"--color-primary-bg": "#fff6b8",
				"--color-primary-bg-light": "#ffffff",
				"--color-accent": "#ffdd00",
				"--color-accent-rgb": "255, 221, 0",
				"--color-accent-light": "#f7d046",
				"--color-bg-primary": "#e5e7eb",
				"--color-bg-secondary": "#ffffff",
				"--color-bg-primary-light": "#f3f4f6",
				"--color-bg-primary-deep": "#fafafa",
				"--color-bg-primary-dark": "#171510",
				"--color-bg-secondary-dark": "#222222",
				"--color-text-primary": "#222222",
				"--color-text-secondary": "#414141",
				"--color-text-tertiary": "#717171",
				"--color-text-primary-dark": "#fff8d1",
				"--color-text-secondary-dark": "#f5f0c4",
				"--color-text-tertiary-dark": "#c7bd78",
				"--color-btn-primary": "#ffdd00",
				"--color-btn-primary-hover": "#f7d046",
				"--color-btn-primary-dark": "#ffdd00",
				"--color-btn-primary-dark-hover": "#f7d046",
				"--color-btn-primary-text": "#000000",
			},
			dark: {
				"--color-primary": "#ffdd00",
				"--color-primary-rgb": "255, 221, 0",
				"--color-primary-strong": "#f7d046",
				"--color-primary-light": "#fff2a6",
				"--color-primary-dark": "#ffdd00",
				"--color-primary-light-dark": "#ffdd00",
				"--color-primary-lighter": "#fff2a6",
				"--color-primary-bg": "rgba(255, 221, 0, 0.15)",
				"--color-primary-bg-light": "rgba(255, 221, 0, 0.07)",
				"--color-accent": "#d8573f",
				"--color-accent-rgb": "216, 87, 63",
				"--color-accent-light": "#f5d5cf",
				"--color-bg-primary": "#171510",
				"--color-bg-secondary": "#222222",
				"--color-bg-primary-light": "#1f1c13",
				"--color-bg-primary-deep": "#100f0b",
				"--color-bg-primary-dark": "#171510",
				"--color-bg-secondary-dark": "#222222",
				"--color-text-primary": "#fff8d1",
				"--color-text-secondary": "#f5f0c4",
				"--color-text-tertiary": "#c7bd78",
				"--color-text-primary-dark": "#fff8d1",
				"--color-text-secondary-dark": "#f5f0c4",
				"--color-text-tertiary-dark": "#c7bd78",
				"--color-btn-primary": "#ffdd00",
				"--color-btn-primary-hover": "#f7d046",
				"--color-btn-primary-dark": "#ffdd00",
				"--color-btn-primary-dark-hover": "#f7d046",
				"--color-btn-primary-text": "#000000",
			},
		},
	},
	{
		id: "precision-orange",
		name: "Precision Orange",
		description:
			"技术向中性配色，冷灰表面、黑色文字，一抹精准的橙色信号。",
		source: "技术中性色板",
		designDoc: "docs/DESIGN/precision-orange.md",
		details: {
			atmosphere:
				"技术极简风，单色结构加工程级清晰度，单一橙色指示器。",
			bestFor: ["开发者工具", "CLI 产品", "AI 工程平台", "技术文档"],
			colorRoles: [
				{ name: "工厂黑", value: "#020202", role: "主要文字和强烈的交互对比（Factory Black）" },
				{ name: "工厂浅灰", value: "#eeeeee", role: "页面画布和安静表面（Factory Gray）" },
				{ name: "代码橙", value: "#ef6f2e", role: "状态标签和高注意力信号（Code Orange）" },
			],
			guidance: [
				"橙色点到为止，只标记新的、活跃的或技术信号状态。",
				"靠黑、灰和间距撑起层次，不做多余装饰。",
				"色板干净，功能至上。",
			],
		},
		swatches: ["#020202", "#3d3a39", "#ef6f2e", "#eeeeee", "#fafafa"],
		lightSwatches: ["#020202", "#3d3a39", "#b8b3b0", "#ef6f2e", "#eeeeee", "#fafafa"],
		darkSwatches: ["#ff9a62", "#f2e8e2", "#d8cbc3", "#2a2623", "#101010", "#1a1817"],
		tokens: {
			light: {
				"--color-primary": "#020202",
				"--color-primary-rgb": "2, 2, 2",
				"--color-primary-strong": "#3d3a39",
				"--color-primary-dark": "#020202",
				"--color-primary-light": "#b8b3b0",
				"--color-primary-light-dark": "#ff9a62",
				"--color-primary-lighter": "#d8d5d2",
				"--color-primary-bg": "#e6e4e2",
				"--color-primary-bg-light": "#fafafa",
				"--color-accent": "#ef6f2e",
				"--color-accent-rgb": "239, 111, 46",
				"--color-accent-light": "#ffb08a",
				"--color-bg-primary": "#eeeeee",
				"--color-bg-secondary": "#fafafa",
				"--color-bg-primary-light": "#f4f4f4",
				"--color-bg-primary-deep": "#ffffff",
				"--color-bg-primary-dark": "#101010",
				"--color-bg-secondary-dark": "#1a1817",
				"--color-text-primary": "#020202",
				"--color-text-secondary": "#3d3a39",
				"--color-text-tertiary": "#756f6b",
				"--color-text-primary-dark": "#f2e8e2",
				"--color-text-secondary-dark": "#d8cbc3",
				"--color-text-tertiary-dark": "#a49d9a",
				"--color-btn-primary": "#020202",
				"--color-btn-primary-hover": "#3d3a39",
				"--color-btn-primary-dark": "#ff9a62",
				"--color-btn-primary-dark-hover": "#ffb08a",
				"--color-btn-primary-text": "#ffffff",
			},
			dark: {
				"--color-primary": "#ff9a62",
				"--color-primary-rgb": "255, 154, 98",
				"--color-primary-strong": "#ffb08a",
				"--color-primary-light": "#ffd2bd",
				"--color-primary-dark": "#ff9a62",
				"--color-primary-light-dark": "#ff9a62",
				"--color-primary-lighter": "#ffd2bd",
				"--color-primary-bg": "rgba(255, 154, 98, 0.15)",
				"--color-primary-bg-light": "rgba(255, 154, 98, 0.07)",
				"--color-accent": "#ef6f2e",
				"--color-accent-rgb": "239, 111, 46",
				"--color-accent-light": "#ffb08a",
				"--color-bg-primary": "#101010",
				"--color-bg-secondary": "#1a1817",
				"--color-bg-primary-light": "#171615",
				"--color-bg-primary-deep": "#090909",
				"--color-bg-primary-dark": "#101010",
				"--color-bg-secondary-dark": "#1a1817",
				"--color-text-primary": "#f2e8e2",
				"--color-text-secondary": "#d8cbc3",
				"--color-text-tertiary": "#a49d9a",
				"--color-text-primary-dark": "#f2e8e2",
				"--color-text-secondary-dark": "#d8cbc3",
				"--color-text-tertiary-dark": "#a49d9a",
				"--color-btn-primary": "#ff9a62",
				"--color-btn-primary-hover": "#ffb08a",
				"--color-btn-primary-dark": "#ff9a62",
				"--color-btn-primary-dark-hover": "#ffb08a",
				"--color-btn-primary-text": "#101010",
			},
		},
	},
	{
		id: "comic-pulp",
		name: "Comic Pulp",
		description:
			"柔和纸浆漫画风，淡纸背景、葡萄紫结构、柠檬黄操作与图形化墨色对比。",
		source: "柔和漫画色板",
		designDoc: "docs/DESIGN/comic-pulp.md",
		details: {
			atmosphere:
				"柔和纸浆漫画质感：淡纸画布打底，葡萄紫结构撑骨架，柠檬黄与墨色形成对比。",
			bestFor: ["趣味品牌", "活动页", "游戏", "创意发布"],
			colorRoles: [
				{ name: "葡萄墨", value: "#6b5fb5", role: "标题、链接和品牌结构（Grape Ink）" },
				{ name: "柠檬黄", value: "#f2dc4d", role: "主要操作和明快强调（Lemon Drop）" },
				{ name: "纸浆白", value: "#fbf7ea", role: "柔和页面背景（Pulp Paper）" },
			],
			guidance: [
				"页面背景保持淡雅，给漫画色留出呼吸空间。",
				"黄色管操作和强调，葡萄紫文字代替纯黑。",
				"靠色彩对比营造图形感，别让整页糊成一片饱和色。",
			],
		},
		swatches: ["#6b5fb5", "#c8c1f0", "#f2dc4d", "#fbf7ea", "#241c3d"],
		lightSwatches: ["#6b5fb5", "#3f357d", "#c8c1f0", "#f2dc4d", "#fbf7ea", "#fffdf5"],
		darkSwatches: ["#f2dc4d", "#c8c1f0", "#f6cc5f", "#3f357d", "#18152d", "#252040"],
		tokens: {
			light: {
				"--color-primary": "#6b5fb5",
				"--color-primary-rgb": "107, 95, 181",
				"--color-primary-strong": "#3f357d",
				"--color-primary-dark": "#6b5fb5",
				"--color-primary-light": "#c8c1f0",
				"--color-primary-light-dark": "#f2dc4d",
				"--color-primary-lighter": "#e8e4ff",
				"--color-primary-bg": "#eeeaff",
				"--color-primary-bg-light": "#fffdf5",
				"--color-accent": "#f2dc4d",
				"--color-accent-rgb": "242, 220, 77",
				"--color-accent-light": "#f6cc5f",
				"--color-bg-primary": "#fbf7ea",
				"--color-bg-secondary": "#fffdf5",
				"--color-bg-primary-light": "#f4efff",
				"--color-bg-primary-deep": "#fffaf0",
				"--color-bg-primary-dark": "#18152d",
				"--color-bg-secondary-dark": "#252040",
				"--color-text-primary": "#241c3d",
				"--color-text-secondary": "#473f67",
				"--color-text-tertiary": "#806f4b",
				"--color-text-primary-dark": "#f2dc4d",
				"--color-text-secondary-dark": "#f6f0d1",
				"--color-text-tertiary-dark": "#c8c1f0",
				"--color-btn-primary": "#f2dc4d",
				"--color-btn-primary-hover": "#f6cc5f",
				"--color-btn-primary-dark": "#f2dc4d",
				"--color-btn-primary-dark-hover": "#f6cc5f",
				"--color-btn-primary-text": "#241c3d",
			},
			dark: {
				"--color-primary": "#f2dc4d",
				"--color-primary-rgb": "242, 220, 77",
				"--color-primary-strong": "#f6cc5f",
				"--color-primary-light": "#fff2a6",
				"--color-primary-dark": "#f2dc4d",
				"--color-primary-light-dark": "#f2dc4d",
				"--color-primary-lighter": "#fff2a6",
				"--color-primary-bg": "rgba(242, 220, 77, 0.16)",
				"--color-primary-bg-light": "rgba(242, 220, 77, 0.08)",
				"--color-accent": "#c8c1f0",
				"--color-accent-rgb": "200, 193, 240",
				"--color-accent-light": "#e8e4ff",
				"--color-bg-primary": "#18152d",
				"--color-bg-secondary": "#252040",
				"--color-bg-primary-light": "#211c3a",
				"--color-bg-primary-deep": "#100e20",
				"--color-bg-primary-dark": "#18152d",
				"--color-bg-secondary-dark": "#252040",
				"--color-text-primary": "#f2dc4d",
				"--color-text-secondary": "#f6f0d1",
				"--color-text-tertiary": "#c8c1f0",
				"--color-text-primary-dark": "#f2dc4d",
				"--color-text-secondary-dark": "#f6f0d1",
				"--color-text-tertiary-dark": "#c8c1f0",
				"--color-btn-primary": "#f2dc4d",
				"--color-btn-primary-hover": "#f6cc5f",
				"--color-btn-primary-dark": "#f2dc4d",
				"--color-btn-primary-dark-hover": "#f6cc5f",
				"--color-btn-primary-text": "#241c3d",
			},
		},
	},
	{
		id: "midnight-pastel",
		name: "Midnight Pastel",
		description:
			"深色协作风配色，黑色画布、柔和粉彩卡片、紫色点缀与暖陶土操作色。",
		source: "深色粉彩色板",
		designDoc: "docs/DESIGN/midnight-pastel.md",
		details: {
			atmosphere:
				"暗夜上的哑光粉彩块：深色工作空间，紫色、赭色、玫瑰和陶土柔和点缀。",
			bestFor: ["创意工作空间", "协作工具", "项目仪表盘", "工作室"],
			colorRoles: [
				{ name: "暗夜画布", value: "#000000", role: "深色页面基底（Midnight Canvas）" },
				{ name: "暖紫", value: "#bbb2ce", role: "突出点缀和项目卡片活力（Warm Violet）" },
				{ name: "大地陶", value: "#65451d", role: "沉稳的主要操作色（Earth Clay）" },
			],
			guidance: [
				"深色底色承载界面，粉彩只做克制的亮色点缀。",
				"陶土和赭色做暖调操作色，不用通用亮色。",
				"避开刺眼霓虹色，保持哑光触感。",
			],
		},
		swatches: ["#000000", "#bbb2ce", "#e4b976", "#65451d", "#cb9da2"],
		lightSwatches: ["#453b60", "#bbb2ce", "#e4b976", "#65451d", "#f3f1ec", "#ffffff"],
		darkSwatches: ["#bbb2ce", "#e4b976", "#cb9da2", "#65451d", "#000000", "#121212"],
		tokens: {
			light: {
				"--color-primary": "#453b60",
				"--color-primary-rgb": "69, 59, 96",
				"--color-primary-strong": "#65451d",
				"--color-primary-dark": "#453b60",
				"--color-primary-light": "#bbb2ce",
				"--color-primary-light-dark": "#bbb2ce",
				"--color-primary-lighter": "#d9d2e7",
				"--color-primary-bg": "#ebe7f3",
				"--color-primary-bg-light": "#f3f1ec",
				"--color-accent": "#e4b976",
				"--color-accent-rgb": "228, 185, 118",
				"--color-accent-light": "#f0d6a8",
				"--color-bg-primary": "#f3f1ec",
				"--color-bg-secondary": "#ffffff",
				"--color-bg-primary-light": "#e5e6e1",
				"--color-bg-primary-deep": "#fbfaf6",
				"--color-bg-primary-dark": "#000000",
				"--color-bg-secondary-dark": "#121212",
				"--color-text-primary": "#453b60",
				"--color-text-secondary": "#333333",
				"--color-text-tertiary": "#65451d",
				"--color-text-primary-dark": "#bbb2ce",
				"--color-text-secondary-dark": "#ffffff",
				"--color-text-tertiary-dark": "#e4b976",
				"--color-btn-primary": "#65451d",
				"--color-btn-primary-hover": "#453b60",
				"--color-btn-primary-dark": "#bbb2ce",
				"--color-btn-primary-dark-hover": "#e4b976",
				"--color-btn-primary-text": "#ffffff",
			},
			dark: {
				"--color-primary": "#bbb2ce",
				"--color-primary-rgb": "187, 178, 206",
				"--color-primary-strong": "#e4b976",
				"--color-primary-light": "#d9d2e7",
				"--color-primary-dark": "#bbb2ce",
				"--color-primary-light-dark": "#bbb2ce",
				"--color-primary-lighter": "#d9d2e7",
				"--color-primary-bg": "rgba(187, 178, 206, 0.16)",
				"--color-primary-bg-light": "rgba(187, 178, 206, 0.08)",
				"--color-accent": "#e4b976",
				"--color-accent-rgb": "228, 185, 118",
				"--color-accent-light": "#f0d6a8",
				"--color-bg-primary": "#000000",
				"--color-bg-secondary": "#121212",
				"--color-bg-primary-light": "#0b0b0b",
				"--color-bg-primary-deep": "#000000",
				"--color-bg-primary-dark": "#000000",
				"--color-bg-secondary-dark": "#121212",
				"--color-text-primary": "#bbb2ce",
				"--color-text-secondary": "#ffffff",
				"--color-text-tertiary": "#e4b976",
				"--color-text-primary-dark": "#bbb2ce",
				"--color-text-secondary-dark": "#ffffff",
				"--color-text-tertiary-dark": "#e4b976",
				"--color-btn-primary": "#bbb2ce",
				"--color-btn-primary-hover": "#e4b976",
				"--color-btn-primary-dark": "#bbb2ce",
				"--color-btn-primary-dark-hover": "#e4b976",
				"--color-btn-primary-text": "#000000",
			},
		},
	},
	{
		id: "sky-blue",
		name: "Sky Blue",
		description:
			"淡蓝白产品配色，近白画布、天蓝洗色表面、午夜墨色与鲜明蓝色焦点。",
		source: "淡蓝产品色板",
		designDoc: "docs/DESIGN/sky-blue.md",
		details: {
			atmosphere:
				"磨砂亚麻上的蓝图：近白基底铺开，天蓝洗色铺面，亮蓝色像荧光笔标注重点。",
			bestFor: ["CRM 产品", "SaaS 仪表盘", "管线工具", "效率应用"],
			colorRoles: [
				{ name: "信号蓝", value: "#145aff", role: "链接、聚焦环和高强调操作（Signal Blue）" },
				{ name: "亚麻画布", value: "#fcfcfc", role: "主要页面表面（Linen Canvas）" },
				{ name: "午夜墨色", value: "#020520", role: "密集展示文字和强控件（Midnight Ink）" },
			],
			guidance: [
				"蓝色只做精准信号，别大面积涂抹。",
				"近白和淡蓝表面提供大部分层次感。",
				"次要文字走蓝灰中性色，沉稳且有产品感。",
			],
		},
		swatches: ["#145aff", "#b6cbfd", "#f0f4fe", "#fcfcfc", "#020520"],
		lightSwatches: ["#145aff", "#0f1f3d", "#b6cbfd", "#f0f4fe", "#fcfcfc", "#ffffff"],
		darkSwatches: ["#83a6ff", "#b6cbfd", "#f0f4fe", "#17254a", "#080b1a", "#11182f"],
		tokens: {
			light: {
				"--color-primary": "#145aff",
				"--color-primary-rgb": "20, 90, 255",
				"--color-primary-strong": "#0f1f3d",
				"--color-primary-dark": "#145aff",
				"--color-primary-light": "#b6cbfd",
				"--color-primary-light-dark": "#83a6ff",
				"--color-primary-lighter": "#dbe6ff",
				"--color-primary-bg": "#f0f4fe",
				"--color-primary-bg-light": "#fcfcfc",
				"--color-accent": "#f0f4fe",
				"--color-accent-rgb": "240, 244, 254",
				"--color-accent-light": "#b6cbfd",
				"--color-bg-primary": "#fcfcfc",
				"--color-bg-secondary": "#ffffff",
				"--color-bg-primary-light": "#f0f4fe",
				"--color-bg-primary-deep": "#ffffff",
				"--color-bg-primary-dark": "#080b1a",
				"--color-bg-secondary-dark": "#11182f",
				"--color-text-primary": "#020520",
				"--color-text-secondary": "#374151",
				"--color-text-tertiary": "#696a72",
				"--color-text-primary-dark": "#83a6ff",
				"--color-text-secondary-dark": "#dbe6ff",
				"--color-text-tertiary-dark": "#9dadcf",
				"--color-btn-primary": "#145aff",
				"--color-btn-primary-hover": "#0f1f3d",
				"--color-btn-primary-dark": "#83a6ff",
				"--color-btn-primary-dark-hover": "#b6cbfd",
				"--color-btn-primary-text": "#ffffff",
			},
			dark: {
				"--color-primary": "#83a6ff",
				"--color-primary-rgb": "131, 166, 255",
				"--color-primary-strong": "#b6cbfd",
				"--color-primary-light": "#dbe6ff",
				"--color-primary-dark": "#83a6ff",
				"--color-primary-light-dark": "#83a6ff",
				"--color-primary-lighter": "#dbe6ff",
				"--color-primary-bg": "rgba(131, 166, 255, 0.16)",
				"--color-primary-bg-light": "rgba(131, 166, 255, 0.07)",
				"--color-accent": "#17254a",
				"--color-accent-rgb": "23, 37, 74",
				"--color-accent-light": "#24396e",
				"--color-bg-primary": "#080b1a",
				"--color-bg-secondary": "#11182f",
				"--color-bg-primary-light": "#0c1225",
				"--color-bg-primary-deep": "#050714",
				"--color-bg-primary-dark": "#080b1a",
				"--color-bg-secondary-dark": "#11182f",
				"--color-text-primary": "#83a6ff",
				"--color-text-secondary": "#dbe6ff",
				"--color-text-tertiary": "#9dadcf",
				"--color-text-primary-dark": "#83a6ff",
				"--color-text-secondary-dark": "#dbe6ff",
				"--color-text-tertiary-dark": "#9dadcf",
				"--color-btn-primary": "#83a6ff",
				"--color-btn-primary-hover": "#b6cbfd",
				"--color-btn-primary-dark": "#83a6ff",
				"--color-btn-primary-dark-hover": "#b6cbfd",
				"--color-btn-primary-text": "#080b1a",
			},
		},
	},
	{
		id: "rico-red",
		name: "Rico Red",
		description:
			"务实红点缀主题，暖灰白画布、石墨文字与自信的红色操作色。",
		source: "红色行动色板",
		designDoc: "docs/DESIGN/rico-red.md",
		details: {
			atmosphere:
				"洁净纸面上的云端控制面板：企业级清晰、暖灰调、强排版，一抹自信红色。",
			bestFor: ["B2B SaaS", "基础设施工具", "安全产品", "企业文档"],
			colorRoles: [
				{ name: "行动红", value: "#d04841", role: "主要操作按钮和激活状态（Action Red）" },
				{ name: "石墨黑", value: "#181717", role: "标题和强调文字（Graphite Black）" },
				{ name: "画布灰", value: "#eeebea", role: "温暖的页面背景（Canvas Pale）" },
			],
			guidance: [
				"红色只用在主要操作或明确的激活状态。",
				"暖灰表面柔和企业配色的冷硬感。",
				"强文字对比加简洁卡片，少做装饰。",
			],
		},
		swatches: ["#d04841", "#181717", "#2e2d2d", "#eeebea", "#ffffff"],
		lightSwatches: ["#d04841", "#a83b35", "#181717", "#d5d3d2", "#eeebea", "#ffffff"],
		darkSwatches: ["#ff867f", "#f7f2ef", "#e7e1df", "#3a3635", "#181717", "#2e2d2d"],
		tokens: {
			light: {
				"--color-primary": "#d04841",
				"--color-primary-rgb": "208, 72, 65",
				"--color-primary-strong": "#a83b35",
				"--color-primary-dark": "#d04841",
				"--color-primary-light": "#f2aaa5",
				"--color-primary-light-dark": "#ff867f",
				"--color-primary-lighter": "#f9d4d1",
				"--color-primary-bg": "#f8e6e4",
				"--color-primary-bg-light": "#ffffff",
				"--color-accent": "#eeebea",
				"--color-accent-rgb": "238, 235, 234",
				"--color-accent-light": "#f7f5f4",
				"--color-bg-primary": "#eeebea",
				"--color-bg-secondary": "#ffffff",
				"--color-bg-primary-light": "#f7f5f4",
				"--color-bg-primary-deep": "#ffffff",
				"--color-bg-primary-dark": "#181717",
				"--color-bg-secondary-dark": "#2e2d2d",
				"--color-text-primary": "#181717",
				"--color-text-secondary": "#2e2d2d",
				"--color-text-tertiary": "#706e6d",
				"--color-text-primary-dark": "#f7f2ef",
				"--color-text-secondary-dark": "#e7e1df",
				"--color-text-tertiary-dark": "#b7b1af",
				"--color-btn-primary": "#d04841",
				"--color-btn-primary-hover": "#a83b35",
				"--color-btn-primary-dark": "#ff867f",
				"--color-btn-primary-dark-hover": "#ffb3ae",
				"--color-btn-primary-text": "#ffffff",
			},
			dark: {
				"--color-primary": "#ff867f",
				"--color-primary-rgb": "255, 134, 127",
				"--color-primary-strong": "#ffb3ae",
				"--color-primary-light": "#ffd8d5",
				"--color-primary-dark": "#ff867f",
				"--color-primary-light-dark": "#ff867f",
				"--color-primary-lighter": "#ffd8d5",
				"--color-primary-bg": "rgba(255, 134, 127, 0.16)",
				"--color-primary-bg-light": "rgba(255, 134, 127, 0.07)",
				"--color-accent": "#3a3635",
				"--color-accent-rgb": "58, 54, 53",
				"--color-accent-light": "#4a4544",
				"--color-bg-primary": "#181717",
				"--color-bg-secondary": "#2e2d2d",
				"--color-bg-primary-light": "#201f1f",
				"--color-bg-primary-deep": "#111010",
				"--color-bg-primary-dark": "#181717",
				"--color-bg-secondary-dark": "#2e2d2d",
				"--color-text-primary": "#f7f2ef",
				"--color-text-secondary": "#e7e1df",
				"--color-text-tertiary": "#b7b1af",
				"--color-text-primary-dark": "#f7f2ef",
				"--color-text-secondary-dark": "#e7e1df",
				"--color-text-tertiary-dark": "#b7b1af",
				"--color-btn-primary": "#ff867f",
				"--color-btn-primary-hover": "#ffb3ae",
				"--color-btn-primary-dark": "#ff867f",
				"--color-btn-primary-dark-hover": "#ffb3ae",
				"--color-btn-primary-text": "#181717",
			},
		},
	},
];

export const themeById = Object.fromEntries(themes.map((theme) => [theme.id, theme]));
